AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an SQS queue for the Vulnerability Management System.

Resources:
  VulnerabilityQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: VulnerabilityQueue
      VisibilityTimeout: 300
      MessageRetentionPeriod: 86400
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
        maxReceiveCount: 5

  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: DeadLetterQueue
      MessageRetentionPeriod: 1209600

Outputs:
  VulnerabilityQueueURL:
    Description: URL of the main SQS queue
    Value: !Ref VulnerabilityQueue

  VulnerabilityQueueARN:
    Description: ARN of the main SQS queue
    Value: !GetAtt VulnerabilityQueue.Arn

  DeadLetterQueueURL:
    Description: URL of the dead-letter SQS queue
    Value: !Ref DeadLetterQueue

  DeadLetterQueueARN:
    Description: ARN of the dead-letter SQS queue
    Value: !GetAtt DeadLetterQueue.Arn