AWSTemplateFormatVersion: "2010-09-09"
Description: "Creates a PostgreSQL RDS Database configured for Dev/Test environments."

Parameters:
  DBName:
    Type: String
    Default: devtestdb
    Description: "The database name."

  DBUsername:
    Type: String
    Default: devuser
    Description: "Database admin username."
    AllowedPattern: "[a-zA-Z0-9]+"
    ConstraintDescription: "must be alphanumeric."

  DBPassword:
    Type: String
    Description: "Database admin password (min 8 chars, at least one number)."
    NoEcho: true
    MinLength: 12
    AllowedPattern: "(?=.*[0-9])(?=.*[a-zA-Z]).+"
    ConstraintDescription: "must have at least one number and one letter."

  DBInstanceClass:
    Type: String
    Default: db.t3.micro
    AllowedValues:
      - db.t3.micro
      - db.t3.small
      - db.t3.medium
    Description: "RDS Instance Type suitable for Dev/Test environments."

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: "Select your VPC ID."

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: "Select at least two private subnets in the VPC."

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Subnet group for PostgreSQL RDS"
      SubnetIds: !Ref SubnetIds

  DBInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow PostgreSQL access from within the VPC"
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: "10.0.0.0/16" # Adjust to your VPC CIDR block for security

  PostgreSQLRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref DBName
      Engine: postgres
      EngineVersion: "16.4-R2" # Ensure this version is available in your region
      DBInstanceClass: !Ref DBInstanceClass
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      AllocatedStorage: 20
      StorageType: gp2
      BackupRetentionPeriod: 1 # Shorter retention for Dev/Test
      MultiAZ: false # Single-AZ for Dev/Test environments
      PubliclyAccessible: false
      StorageEncrypted: true
      VPCSecurityGroups:
        - !GetAtt DBInstanceSecurityGroup.GroupId
      DBSubnetGroupName: !Ref DBSubnetGroup
      DeletionProtection: false

Outputs:
  PostgreSQLEndpoint:
    Description: "Endpoint address of the PostgreSQL instance"
    Value: !GetAtt PostgreSQLRDSInstance.Endpoint.Address

  PostgreSQLPort:
    Description: "Port of the PostgreSQL instance"
    Value: !GetAtt PostgreSQLRDSInstance.Endpoint.Port